---
- block:
    - name: Updating server using 'apt update'
      apt:
        state: latest
        upgrade: yes
        update_cache: yes
        autoclean: yes
        autoremove: yes
      tags: apt_update

    - name: Installing some necessary packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items: '{{ debian.packages}}'
      tags: basic_packages

    - name: Allowing SSH service in ufw firewall
      ufw:
        rule: allow
        port: 22
      tags: firewall

    - name: Enabling Logging in ufw firewall service
      ufw:
        logging: on
      tags: firewall


    - name: Starting ufw firewall service
      ufw:
        state: disabled
        policy: accept
      tags: firewall

    - name: Rebooing Machine
      reboot:
        msg: "Reboot initiated by Ansible, event: system update"
        reboot_timeout: 600
        post_reboot_delay: 300
      tags:
        - reboot
        - server_reboot
      when: server_update.changed
      register: server_reboot
