---
- block:
    - name: Updating server using 'apt update'
      apt:
        state: latest
        upgrade: yes
        update_cache: yes
        autoclean: yes
        autoremove: yes
      tags: apt_update

    - name: Installing some necessary packages
      apt:
        name: "{{ item }}"
        state: latest
      with_items: '{{ debian.packages}}'
      tags: basic_packages

    - name: Allowing SSH service in ufw firewall
      ufw: 
        rule: allow
        port: 22
      tags: firewall

    - name: Enabling Logging in ufw firewall service
      ufw: 
        logging: on
      tags: firewall
    

    - name: Starting ufw firewall service
      ufw: 
        state: enabled
        policy: reject
      tags: firewall

    - name: Restarting Machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      become: true
      ignore_errors: true
      tags: reboot

    - name: Waiting for server to reboot and come back
      wait_for: 
        host: "{{ inventory_hostname }}"
        state: started 
        delay: 15 
        timeout: 30
      delegate_to: localhost
      become: false
      tags: reboot
