---
- block:
    #- name: cleaning up any unfinished / pending yum transactions
    #  command: yum-complete-transaction --cleanup-only

    - name: Updating server using 'yum update'
      yum:
        name: "*"
        state: latest
        update_cache: yes
        exclude:
          npm
          nodejs
      tags:
        - server_update
        - yum_update
      register: server_update

    - name: completing any unfinished / pending yum transactions
      command: yum-complete-transaction

    - name: Installing some necessary packages
      yum:
        # name: "{{ item }}"
        name: "{{ redhat.packages }}"
        state: latest
        update_cache: yes
      # with_items: "{{ redhat.packages }}"
      tags: basic_packages

    - name: completing any unfinished / pending yum transactions
      command: yum-complete-transaction

    - name: disabling postfix service - user can enable if required
      systemd:
        name: postfix
        state: stopped
        enabled: false

    - name: Increase the maximum number of system handle - nofile and nproc
      template:
        src: limits.j2
        dest: /etc/security/limits.d/ansible_limits.conf

    - name: Setting Up Selinux
      selinux:
        state: "{{ redhat.selinux.state }}"
        policy: "{{ redhat.selinux.policy }}"
      tags: selinux

    - name: ensuring firewalld package is installed
      yum:
        name: firewalld
        state: latest

    - name: stopping firewalld service
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      tags: firewall

    - name: Rebooing Machine
      reboot:
        msg: "Reboot initiated by Ansible, event: system update"
        reboot_timeout: 600
        post_reboot_delay: 300
      tags:
        - reboot
        - server_reboot
      when: server_update.changed
      register: server_reboot
